version: 0
application:
  version: 1.20 # (optional)
  language: go
  ports:
  - port: 8080
    ingress: true
    ingressPath: /
  pre-build:
    commands:
      - cmd: "chmod"
    args:
      - "+x"
      - "script.sh"
  - cmd: "ls"     
  - cmd: "./script.sh"
