version: 0
application:
  name: carmen # (optional) This could be used in the template
  version: 1.20 # (optional)
  ports:
  - port: 8080
    ingress: true
    ingressPath: /
pre-build:
  commands:
  - cmd: touch
    dir: /temp/
    args:
    - "pepe.txt"
